#!/bin/sh
set -e

rm -rf /tmp/*
rm -rf /usr/local/bin/phpdbg
rm -rf /usr/local/bin/php-cgi
rm -rf /usr/src/php.tar*
rm -rf /usr/includes/*
rm -rf /usr/share/man/*
rm -rf /var/cache/apk/*
rm -rf /var/tmp/*

apk del --purge -q .phpize-deps
apk del --purge -q build-base
apk del --purge -q ${PHPIZE_DEPS}

docker-php-source delete
