#!/bin/sh

rm -rf /tmp/*
rm -rf /usr/local/bin/phpdbg
rm -rf /usr/local/bin/php-cgi
rm -rf /usr/includes/*
rm -rf /usr/share/man/*
rm -rf /var/cache/*
rm -rf /var/tmp/*
rm -rf /var/lib/apt/lists/*
rm -rf /var/log/lastlog
rm -rf /var/log/faillog
rm -rf /usr/local/lib/php/test
