#!/bin/sh

# Cache configs.
php artisan config:cache
php artisan event:cache
php artisan route:cache
php artisan view:cache

# Run migrations.
php artisan migrate --force

# Start Octane.
php -d variables_order=EGPCS \
    artisan \
    octane:start \
        --port=80 \
        --host=0.0.0.0 \
        --server=swoole \
        --workers=4 \
        --task-workers=6
