name: Docker Release

on:
  push:
    tags:
      - "*"

jobs:
  push_fpm:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Release (PHP-FPM, ${{ matrix.base-tag }})

    strategy:
      fail-fast: false
      matrix:
        base-tag:
          - 8.1-fpm-alpine
          - 8.0-fpm-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: quay.io/renokico/laravel-base
          tags: |
            type=semver,pattern={{version}}-${{ matrix.base-tag }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.base-tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and Push
        id: docker
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.fpm
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}
          cache-from: |
            type=gha,scope=php-fpm
          cache-to: |
            type=gha,scope=php-fpm
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7

  push_octane:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Release (Octane, ${{ matrix.base-tag }})

    strategy:
      matrix:
        base-tag:
          - 5.0-php8.2-alpine
          - 5.0-php8.1-alpine
          - 5.0-php8.0-alpine
          - 4.8-php8.2-alpine
          - 4.8-php8.1-alpine
          - 4.8-php8.0-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: quay.io/renokico/laravel-base
          tags: |
            type=semver,pattern=octane-{{version}}-${{ matrix.base-tag }}
            type=semver,pattern=octane-{{major}}.{{minor}}-${{ matrix.base-tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and Push
        id: docker
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.octane
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}
          cache-from: |
            type=gha,scope=octane
          cache-to: |
            type=gha,scope=octane
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7

  push_worker:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Release (Worker, ${{ matrix.base-tag }})

    strategy:
      matrix:
        base-tag:
          - 8.2-cli-alpine
          - 8.1-cli-alpine
          - 8.0-cli-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: quay.io/renokico/laravel-base
          tags: |
            type=semver,pattern=worker-{{version}}-${{ matrix.base-tag }}
            type=semver,pattern=worker-{{major}}.{{minor}}-${{ matrix.base-tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and Push
        id: docker
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.worker
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}
          cache-from: |
            type=gha,scope=worker
          cache-to: |
            type=gha,scope=worker
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
