name: Docker Latest

on:
  push:
    branches:
      - master

jobs:
  push_fpm:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Latest (PHP-FPM, ${{ matrix.base-tag }})

    strategy:
      matrix:
        base-tag:
          - 7.4-fpm-alpine
          - 8.0-fpm-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: renokico/laravel-base:latest-${{ matrix.base-tag }}
          file: Dockerfile.fpm
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}

  push_octane:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Latest (Octane, ${{ matrix.base-tag }})

    strategy:
      matrix:
        base-tag:
          - 4.6-php8.0-alpine
          - 4.5-php8.0-alpine
          - 4.6-php7.4-alpine
          - 4.5-php7.4-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: renokico/laravel-base:octane-latest-${{ matrix.base-tag }}
          file: Dockerfile.octane
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}

  push_worker:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Latest (Worker, ${{ matrix.base-tag }})

    strategy:
      matrix:
        base-tag:
          - 8.0-cli-alpine
          - 7.4-cli-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: renokico/laravel-base:worker-latest-${{ matrix.base-tag }}
          file: Dockerfile.worker
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}
