name: Docker Latest

on:
  push:
    branches:
      - master

jobs:
  push_fpm:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Latest (PHP-FPM, ${{ matrix.base-tag }})

    strategy:
      fail-fast: false
      matrix:
        base-tag:
          - 8.1-fpm-alpine
          - 8.0-fpm-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: quay.io/renokico/laravel-base
          tags: |
            type=raw,value=latest-${{ matrix.base-tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.fpm
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}
          cache-from: |
            type=gha,scope=php-fpm
          cache-to: |
            type=gha,scope=php-fpm
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7

  push_swoole:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Latest (${{ matrix.swoole }}/v${{ matrix.swoole-version }} with ${{ matrix.php-tag }})

    strategy:
      fail-fast: false
      matrix:
        php-tag:
          - php8.1-cli-alpine3.15
          - php8.0-cli-alpine3.15
        swoole:
          - openswoole
          - swoole
        include:
          - swoole: openswoole
            swoole-version: "4.12.0"
          - swoole: openswoole
            swoole-version: "4.11.1"
          - swoole: swoole
            swoole-version: "4.8.9"
          - swoole: swoole
            swoole-version: "5.0.1"

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: quay.io/renokico/laravel-base
          tags: |
            type=raw,value=latest-${{ matrix.swoole }}${{ matrix.swoole-version }}-${{ matrix.php-tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.swoole
          build-args: |
            SWOOLE=${{ matrix.swoole }}
            SWOOLE_VERSION=${{ matrix.swoole-version }}
            PHP_TAG=${{ matrix.php-tag }}
          cache-from: |
            type=gha,scope=swoole
          cache-to: |
            type=gha,scope=swoole
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7

  push_worker:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Latest (Worker, ${{ matrix.base-tag }})

    strategy:
      fail-fast: false
      matrix:
        base-tag:
          - 8.1-cli-alpine
          - 8.0-cli-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: quay.io/renokico/laravel-base
          tags: |
            type=raw,value=worker-latest-${{ matrix.base-tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.worker
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}
          cache-from: |
            type=gha,scope=worker
          cache-to: |
            type=gha,scope=worker
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
