name: Docker Commit

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  fpm_push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Commit (PHP-FPM, ${{ matrix.base-tag }})

    strategy:
      fail-fast: false
      matrix:
        base-tag:
          - 7.4-fpm-alpine
          - 8.0-fpm-alpine
          - 8.1-fpm-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: quay.io/renokico/laravel-base:${{ github.sha }}-${{ matrix.base-tag }}
          file: Dockerfile.fpm
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}

  octane_push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Commit (Octane, ${{ matrix.base-tag }})

    strategy:
      fail-fast: false
      matrix:
        base-tag:
          - 4.8-php8.0-alpine
          - 4.7-php8.0-alpine
          - 4.6-php8.0-alpine
          - 4.8-php8.1-alpine
          # - 4.7-php8.1-alpine
          # - 4.6-php8.1-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: quay.io/renokico/laravel-base:octane-${{ github.sha }}-${{ matrix.base-tag }}
          file: Dockerfile.octane
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}

  worker_push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Commit (Worker, ${{ matrix.base-tag }})

    strategy:
      fail-fast: false
      matrix:
        base-tag:
          - 8.1-cli-alpine
          - 8.0-cli-alpine
          - 7.4-cli-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: quay.io/renokico/laravel-base:worker-${{ github.sha }}-${{ matrix.base-tag }}
          file: Dockerfile.worker
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}
